### ISSUE TITLE
Just checking in

### ISSUE THREAD

**Issue by dwmk** [wu-kan/wuk_device_vector#1]
Hey there, Mr Wu Kan!
Uh... sorry for opening up the issue request here. But I was worried about you.
I had sent out emails to the address found on your Github profile and website, but haven't received a reply yet.
So... I hope you're okay. Please check my email when you get free time!

(I opened this issue to inform you since it was your most recent activity. Please delete it after you've read my message.)

Cheers and thanks,

Yours Sincerely,
Dewan Mukto

**Comment by dwmk** [comment]
> In case you are not comfortable with checking your email right now. I can just quote whatever I had written, so you can read it here. 😅 Here it is:

Greetings Mr Wu Kan!

Firstly, I would like to know if you are doing alright, because I saw your GitHub profile's bio had
我的灵魂奏出绝响 written on it, which translates to "My soul is playing its final song" in English. I am very worried if you are feeling very depressed or regretful about something. 😢

Also, I would like to thank you once again for publishing such an awesome and beautiful Jekyll theme for GitHub Pages (https://github.com/wu-kan/wu-kan.github.io). I really liked it! 😄👍

I also reviewed your thesis on "reducing code-size via loop rerolling at binary level" from Google Scholar.

I hope you get well soon, and whatever troubles you may have should go away with time and patience, sir. 💐

(Sorry that I cannot speak Chinese/Mandarin directly, so I have used a translator for the Chinese version of my email)

吴侃先生，您好！

首先，我想知道您是否还好，因为我看到您的 GitHub 个人资料上写着
我的灵魂奏出绝响，英文翻译为“我的灵魂正在演奏它的最后一首歌”。如果您对某事感到非常沮丧或后悔，我会非常担心。😢

此外，我再次感谢您为 GitHub Pages（https://github.com/wu-kan/wu-kan.github.io）发布了如此出色和美丽的 Jekyll 主题。我真的很喜欢它！😄👍

我还在 Google Scholar 上查看了您关于“通过二进制级别的循环重滚减少代码大小”的论文。

希望您早日康复，先生，无论您遇到什么麻烦，都会随着时间和耐心而消失。💐


Yours Sincerely,
Dewan Mukto

**Comment by wu-kan** [comment]
Thank you for your concern and love for my website; it touches my heart. I am sorry for not responding to your message in a timely manner, as I have been busy writing a paper recently. If you have any new feature requests or other ideas regarding this theme, just let me know! "My soul is playing its final song"("奏でろ荒ぶる魂") is a lyric from a song I enjoy, which you can listen to [here](https://www.youtube.com/watch?v=e9Azkg9y-I4).

**Comment by dwmk** [comment]
Oh okay! I misunderstood the lyrics, thinking that maybe you were thinking that. 😅
Hope ya have a great day!
